// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj254oAHj-ZTzefIzclrXXyXjOM3CkC1A',
    appId: '1:4828972715:web:99ebddc902fac91a1459ee',
    messagingSenderId: '4828972715',
    projectId: 'sorteringshjaelperen',
    authDomain: 'sorteringshjaelperen.firebaseapp.com',
    storageBucket: 'sorteringshjaelperen.appspot.com',
    measurementId: 'G-VRD4GMHT43',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjaxgDBF944-ukpwa8T77CgMz9Y1J04oE',
    appId: '1:4828972715:ios:a9dabf3e9e9afe9d1459ee',
    messagingSenderId: '4828972715',
    projectId: 'sorteringshjaelperen',
    storageBucket: 'sorteringshjaelperen.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjaxgDBF944-ukpwa8T77CgMz9Y1J04oE',
    appId: '1:4828972715:ios:a9dabf3e9e9afe9d1459ee',
    messagingSenderId: '4828972715',
    projectId: 'sorteringshjaelperen',
    storageBucket: 'sorteringshjaelperen.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
